In [33]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [39]:
import numpy as np

In [41]:
print(np.__version__)

1.26.4


In [43]:
# arr = np.array([1,2,3,4,5])
# print(arr)
# print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [61]:
# a=np.array(42)

# b = np.array([1,2,3,4,5])

# c = np.array([
#     [1,2,3],
#     [4,5,6]
# ])

# d = np.array([
#     [1,2,3],
#     [4,5,6],
#     [7,8,9]
# ])

In [63]:
# print(a.ndim)
# print(b.ndim)
# print(c.ndim)
# print(d.ndim)

0
1
2
2


In [97]:
s=np.array([1,2,3,4,5,6,7,8,9,10])
print(s[1:5])
print(s[-6:-1])
print(s[0:9:2])
print(s[1:9:-1])
print(s[:9:])
print(s[:])
print(s[: : 2])

[2 3 4 5]
[5 6 7 8 9]
[1 3 5 7 9]
[]
[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [123]:
ch = np.array(["C","G","C"])

if np.array_equal(ch, ch[::-1]):
    print("Palindrome")
else:
    print("Not Palindrome")

Palindrome


In [141]:
# arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# print(arr[1,1:4])
# print(arr[0,1:4])
# print(arr[0:2,1])
# print(arr[0:2,1:4])

[7 8 9]
[2 3 4]
[2 7]
[[2 3 4]
 [7 8 9]]


In [143]:
# print(arr.dtype)

int64


In [ ]:
arr=np.array([0,0,0,0,0])
arr=np.array([1,1,1,1,1,1,1,1])
arr=np.array([100])
arr=np.array([1,3,5,7,9,11,13,15,17,19])
arr = np.arange(5,51,5)

In [ ]:
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [6,2,9]
])

c = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

c = np.array([
    [7,7],
    [7,7],
    [7,7],
    [7,7],
    [7,7],
    [7,7]
])