In [33]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [39]:
import numpy as np

In [41]:
print(np.__version__)

1.26.4


In [43]:
# arr = np.array([1,2,3,4,5])
# print(arr)
# print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [61]:
# a=np.array(42)

# b = np.array([1,2,3,4,5])

# c = np.array([
#     [1,2,3],
#     [4,5,6]
# ])

# d = np.array([
#     [1,2,3],
#     [4,5,6],
#     [7,8,9]
# ])

In [63]:
# print(a.ndim)
# print(b.ndim)
# print(c.ndim)
# print(d.ndim)

0
1
2
2


In [97]:
s=np.array([1,2,3,4,5,6,7,8,9,10])
print(s[1:5])
print(s[-6:-1])
print(s[0:9:2])
print(s[1:9:-1])
print(s[:9:])
print(s[:])
print(s[: : 2])

[2 3 4 5]
[5 6 7 8 9]
[1 3 5 7 9]
[]
[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [123]:
ch = np.array(["C","G","C"])

if np.array_equal(ch, ch[::-1]):
    print("Palindrome")
else:
    print("Not Palindrome")

Palindrome


In [141]:
# arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# print(arr[1,1:4])
# print(arr[0,1:4])
# print(arr[0:2,1])
# print(arr[0:2,1:4])

[7 8 9]
[2 3 4]
[2 7]
[[2 3 4]
 [7 8 9]]


In [143]:
# print(arr.dtype)

int64


In [ ]:
arr=np.array([0,0,0,0,0])
arr=np.array([1,1,1,1,1,1,1,1])
arr=np.array([100])
arr=np.array([1,3,5,7,9,11,13,15,17,19])
arr = np.arange(5,51,5)

In [ ]:
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [6,2,9]
])

c = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

c = np.array([
    [7,7],
    [7,7],
    [7,7],
    [7,7],
    [7,7],
    [7,7]
])

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.shape)

arr.ndim

arr.size

arr.dtype

len(arr)

arr.nbytes

In [ ]:
arr = np.array([1.5,2.7,3.9])

new_arr = arr.astype(int)

print(new_arr)

In [ ]:
arr = np.array([1,2,3])

new_arr = arr.astype(float)

print(new_arr)

In [ ]:
arr = np.array([
 [1,2,3],
 [4,5,6]
])

print(arr.size)

In [155]:
arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[4])
print(arr[2])
print(arr[0:4])
print(arr[:: -1])
print(arr[0])

10
50
30
[10 20 30 40]
[50 40 30 20 10]


In [157]:
arr = np.array([10,20,30,40,50,60])
print(arr[1:7])
print(arr[0:7:1])


[20 30 40 50 60]


In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matrix[0]
matrix[-1]
matrix[:,0]
matrix[:,-1]
matrix[:2,:2]
matrix[1:,1:]

In [ ]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a+b)

In [ ]:
a = np.array([10,20,30])

b = np.array([1,2,3])

print(a-b)

In [ ]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a*b)

In [ ]:
a = np.array([10,20,30])

b = np.array([2,4,5])

print(a/b)

In [ ]:
arr = np.array([1,2,3,4])

print(arr**2)

In [ ]:
arr = np.array([1,2,3])

print(arr**3)

In [ ]:
arr = np.array([1,4,9,16])

print(np.sqrt(arr))

In [ ]:
arr = np.array([1,2,3])

print(np.exp(arr))

In [ ]:
angles = np.array([0,np.pi/2,np.pi])

print(np.sin(angles))

In [ ]:
angles = np.array([0,np.pi/2,np.pi])

print(np.cos(angles))

In [ ]:
angles = np.array([0,np.pi/4])

print(np.tan(angles))

In [ ]:
arr = np.array([-10,-5,3,-2])

print(np.abs(arr))

In [159]:
arr = np.array([1,2,3,4,5])

print(arr % 2)

[1 0 1 0 1]
