In [ ]:
import numpy as np 

In [2]:
# arr = np.array([1,2,3,4,5])
# x=arr.copy()
# arr[0]=42
# print(arr)
# print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
# arr = np.array([1,2,3,4,5])
# x=arr.view()
# arr[0]=42
# print(arr)
# print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [14]:
# arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# print(arr)

# new_arr = arr.reshape(4,3)
# print(new_arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
# arr1 = np.array([1,2,3])
# arr2 = np.array([4,5,6])
# arr = np.stack((arr1,arr2),axis=1)
# print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [26]:
#  d = np.array([
#     [1,2,3],
#     [4,5,6],
#     [7,8,9],
#     [10,11,12],
#     [13,14,15],
#     [16,17,18]])
# x= np.array_split(d,3)
# print(x)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
# arr1= np.array([
#     [1,2,3],
#     [4,5,6],
#     [7,8,9]])
# arr2= np.array([
#     [10,11,12],
#     [13,14,15],
#     [16,17,18]])

In [44]:
# A= arr1+arr2
# print(A) 

# print(" ")

# B= arr2-arr1
# print(B)

# print(" ")

# C= arr1*arr2
# print(C)

# print(" ")

# D= arr2/arr1
# print(D)


[5 7 9]
 
[3 3 3]
 
[ 4 10 18]
 
[4.  2.5 2. ]


In [64]:
# A= np.array([
#     [1,2,3],
#     [4,5,6]
#            ])
# print("sum of array: ",np.sum(A))
# print("Mean of array: ",np.mean(A))
# print("Standard deviation of array: ",np.std(A))
# print("Minimum of array: ",np.min(A))
# print("Maximum of array: ",np.max(A))
# print("Index of maximum of array: ",np.argmax(A))

sum of array:  21
Mean of array:  3.5
Standard deviation of array:  1.707825127659933
Minimum of array:  1
Maximum of array:  6
Index of maximum of array:  5


In [70]:
# Matrix= np.array([
#     [1,2,3],
#     [4,5,6]
#            ])
# Vector = np.array([7,8,9])
# result = Matrix+Vector
# print(result)

[[ 8 10 12]
 [11 13 15]]
