In [ ]:
import numpy as np 

In [2]:
# arr = np.array([1,2,3,4,5])
# x=arr.copy()
# arr[0]=42
# print(arr)
# print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
# arr = np.array([1,2,3,4,5])
# x=arr.view()
# arr[0]=42
# print(arr)
# print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [14]:
# arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# print(arr)

# new_arr = arr.reshape(4,3)
# print(new_arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
# arr1 = np.array([1,2,3])
# arr2 = np.array([4,5,6])
# arr = np.stack((arr1,arr2),axis=1)
# print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
 d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
    [13,14,15],
    [16,17,18]])
x= np.array_split(d,2)
print(arr)

[[1 4]
 [2 5]
 [3 6]]
