In [ ]:
import numpy as np 

In [2]:
# arr = np.array([1,2,3,4,5])
# x=arr.copy()
# arr[0]=42
# print(arr)
# print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
# arr = np.array([1,2,3,4,5])
# x=arr.view()
# arr[0]=42
# print(arr)
# print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# x = np.reshape()
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
