# NumPy Student Workbook

Questions only. Write answers in the empty code cells below each question.

Q1. Create a NumPy array containing 10, 20, 30, 40, 50.

In [6]:
import numpy as np

In [8]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


Q2. Create numbers from 1 to 20.

In [14]:
arr = np.arange(1, 21)

for i in range(len(arr)):
    print(arr[i])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


Q3. Create even numbers from 2 to 20.

In [18]:
import numpy as np

arr = np.arange(2, 21 , 2)

for i in range(len(arr)):
    print(arr[i])

2
4
6
8
10
12
14
16
18
20


Q4. Create a 3×4 matrix of zeros.

In [20]:
arr = np.zeros((3, 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Q5. Create a 4×3 matrix of ones.

In [22]:
arr = np.ones((3, 4))

print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Q6. Generate 10 evenly spaced values between 0 and 1.

In [46]:
arr = np.linspace(0, 1, 10)

print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Q7. Create a 2×3 array and find shape, ndim and dtype.

In [38]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


Q8. Create a 4×5 array and find shape, size and ndim.

In [40]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2
(4, 5)


Q9. Convert [1,2,3,4,5] to float datatype.

In [44]:
arr= np.array([1,2,3,4,5])
new_arr=arr.astype(float)
print(new_arr)

[1. 2. 3. 4. 5.]


Q10. Create numbers 1–12 and reshape into 3×4, 2×6 and 4×3.

In [56]:
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape(3,4)
print(arr1)
print(' ')
arr2=arr.reshape(2,6)
print(arr2)
print(' ')
arr3=arr.reshape(4,3)
print(arr3)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q11. Create np.arange(20) and reshape into 4×5 and 5×4.

In [62]:
arr = np.arange(1, 21)

for i in range(len(arr)):
    print(arr[i])
print(" ")

arr1=arr.reshape(4,5)
print(arr1)
print(" ")
arr2=arr.reshape(5,4)
print(arr2)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


Q12. Explain why np.arange(10).reshape(3,4) produces an error.

In [ ]:
because it need 12 elements to make a 3*4 matrix

Q13. Using a 4×4 array, extract the first element.

In [66]:
arr= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr[0][0])

1


Q14. Extract the value 10 from a 4×4 array created using arange.

In [70]:
arr = np.arange(16).reshape(4,4)
print(arr)
print(arr[2][2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10


Q15. Extract the last element.

In [76]:
arr = np.arange(16).reshape(4,4)
print(arr)
print(arr[3][3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
15


Q16. Extract the first row.

In [78]:
print(arr[0])

[0 1 2 3]


Q17. Extract the third row.

In [80]:
print(arr[2])

[ 8  9 10 11]


Q18. Extract the second column.

In [82]:
second_col = arr[:, 1]

print(second_col)

[ 1  5  9 13]


Q19. Extract the last column.

In [86]:
last_col = arr[:, 3]

print(last_col)

[ 3  7 11 15]


Q20. Extract first two rows.

In [90]:
print(arr[0],arr[1])

[0 1 2 3] [4 5 6 7]


Q21. Extract last two rows.

In [92]:
print(arr[2],arr[3])

[ 8  9 10 11] [12 13 14 15]


Q22. Extract first three columns.

In [108]:
arr = np.arange(16).reshape(4,4)
print(arr)
print(" ")
print(arr[:, 0],arr[:, 1],arr[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
 
[ 0  4  8 12] [ 1  5  9 13] [ 2  6 10 14]


Q23. Extract last two columns.

In [106]:
arr = np.arange(16).reshape(4,4)
print(arr)
print(" ")
print(arr[:, 2],arr[:, 3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
 
[ 2  6 10 14] [ 3  7 11 15]


Q24. Extract a 2×2 center block.

In [121]:
arr = np.arange(16).reshape(4,4)
print(arr)
print(" ")

center = arr[1:3, 1:3]
print(center)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
 
[[ 5  6]
 [ 9 10]]


Q25. Extract bottom-right 3×3 block.

In [123]:
br = arr[1:4, 1:4]
print(br)

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


Q26. Extract center element.

In [133]:
arr = np.arange(15).reshape(5,3)
print(arr)
print(arr[2,1])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
7


Q27. Extract center 3×3 block.

In [143]:
center = arr[1:4, 0:3]
print(center)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Q28. Extract top-right corner block.

Q29. Extract bottom-left corner block.

Q30. Extract the main diagonal manually using slicing/indexing.

Q31. Extract every alternate row.

Q32. Extract every alternate column.

Q33. Reverse the rows.

Q34. Reverse the columns.

Q35. Reverse the entire matrix.

Q36. Extract a 3×3 reversed center block.

Q37. Extract only the corner elements.

Q38. Extract only the border elements.

Q39. Increase sales [100,200,300,400] by 10.

Q40. Increase salaries by 15%.

Q41. Apply 18% GST to prices.

Q42. Subtract 5 from every element.

Q43. Find total sales.

Q44. Find average sales.

Q45. Find maximum sales.

Q46. Find minimum sales.

Q47. Find standard deviation.

Q48. Find variance.

Q49. Find median.

Q50. Mini Project: Analyze a sales dataset using NumPy.

In [1]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])

data.shape

(1000, 10)

In [2]:
data

array([[ 1001,    52,     2, ...,     2, 18737,     2],
       [ 1002,    93,    15, ...,     4, 12728,     2],
       [ 1003,    15,     8, ...,     1, 16726,     2],
       ...,
       [ 1998,    18,    11, ...,     3, 18505,     4],
       [ 1999,   100,     1, ...,     3, 10564,     1],
       [ 2000,    86,     7, ...,     5, 19793,     3]])

Q1. Dataset Exploration

Find:

Shape
Number of Dimensions
Datatype
Total Number of Elements

Q2. First Look at Data

Display:

First 10 rows

Last 10 rows

Q3. Using the Sales column:(Sales Column number 5)

Find:

Total Sales

Average Sales

Maximum Sales

Minimum Sales

Q4. Using the Profit column:(column number 6)

Find:

Total Profit

Average Profit

Maximum Profit

Q5. Indexing Challenge

Display:

Row 100

Row 500

Row 999

Q6. Slicing Challenge

Display:

Rows 100–200

First 5 columns

Last 3 columns

Q7. Advanced Slicing

Display:

Every alternate row

Every alternate column

Dataset in reverse order

Q8. Broadcasting

Management decides to increase all sales by 10%.

Create a new sales array with updated values.

Q9. Business Filtering

Find:

Number of orders where Sales > ₹25,000

Number of orders where Profit > ₹5,000

Q10. Management Report

Create a final report showing:

Total Sales

Average Sales

Total Profit

Average Profit

Highest Sale

Highest Profit

Number of High-Value Orders (Sales > ₹25,000)