<font size="6"><b>What is NumPy?</b></font><br>
NumPy is a Python library used for working with arrays.<br>
It also has functions for working in domain of linear algebra, fourier transform, and matrices.<br>
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.<br>
NumPy stands for Numerical Python.

<font size="6"><b>Why Use NumPy?</b></font> <br>
In Python we have lists that serve the purpose of arrays, but they are slow to process.<br>
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.<br>
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.<br>
Arrays are very frequently used in data science, where speed and resources are very important.

<font size="6"> <b>pip install numpy<b></font>

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.2.6


<b>NumPy Creating Arrays<br>
NumPy is used to work with arrays. The array object in NumPy is called ndarray.<br>
We can create a NumPy ndarray object by using the array() function.</B>

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


<b>Dimensions in Arrays<br>
A dimension in arrays is one level of array depth (nested arrays).</b>

<b>0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.</b>

In [6]:
import numpy as np

arr = np.array(42)

print(arr)

42


<b>An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.</b>

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


<b>2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array. 
These are often used to represent matrix or 2nd order tensors.</b>

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


<b>3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.</b>

In [2]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


<font size="6">Check Number of Dimensions?</font> <br>
<b>NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.</b>

In [6]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [4]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
arr = np.array([1, 2, 3, 4]) #get index of array
print(arr[3])

4


In [6]:
import numpy as np   #adding numbers on different indexes 

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [7]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  #accesing 2-d array

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [8]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


<b>Negative Indexing
Use negative indexing to access an array from the end.</b>

In [10]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[0, -1])

Last element from 2nd dim:  5


<font size="6"> <b>Slicing arrays</b></font> <br> <hr>
Slicing in python means taking elements from one given index to another given index.<br><hr>

We pass slice instead of index like this: [start:end].<br><hr>

We can also define the step, like this: [start:end:step].<br><hr>

If we don't pass start its considered 0<br><hr>

If we don't pass end its considered length of array in that dimension<br><hr>

If we don't pass step its considered 1

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


<b>STEP
Use the step value to determine the step of the slicing</b>

In [20]:
import numpy as np   #Return every other element from index 1 to index 5

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [21]:
import numpy as np      #Return every other element from the entire array

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


<b>Slicing 2-D Arrays</b>

In [24]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [11]:
import numpy as np     #From both elements, return index 2

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1])

[2 7]


In [30]:
import numpy as np  #From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


<font size="5"><b>NumPy Data Types</b></font>

<b> NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc. </b>.<br>

Below is a list of all data types in NumPy and the characters used to represent them. <br>

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )



<b>The NumPy array object has a property called dtype that returns the data type of the array:</b>

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [5]:
import numpy as np  #Get the data type of an array containing strings:

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


<font size="5"><b>NumPy Array Copy vs View</b></font>

<b>The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.<br><hr>
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.<br><hr>
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.</b>



In [8]:
import numpy as np
 #Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [10]:
import numpy as np #Make a view, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


<font size="6">NumPy Array Shape</font>

<font size="3">The shape of an array is the number of elements in each dimension.<br>
NumPy arrays have an attribute called <b>shape</b> that returns a tuple with each index having the number of corresponding elements.</font>


In [13]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


<b>The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.</b>

<font size="6">NumPy Array Reshaping</font>


- <b>Reshaping means changing the shape of an array.</b>
- <b>The shape of an array is the number of elements in each dimension. </b>
- <b>By reshaping we can add or remove dimensions or change number of elements in each dimension.</b>


<font size="5">Reshape From 1-D to 2-D</font>

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


<font size="5"> Reshape From 1-D to 3-D </font>

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


<font size="5"> Flattening the arrays</font>

In [28]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)




[[1 2 3]
 [4 5 6]]


In [26]:
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


<font size="6"><b>NumPy Array Iterating<b/></font>

* <b>Iterating means going through elements one by one.</b>
* <b>As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.</b>
* <b>If we iterate on a 1-D array it will go through each element one by one.</b>

In [32]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [34]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [35]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


<font size="6"> NumPy Joining Array </font>

- Joining means putting contents of two or more arrays in a single array.
- In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
- We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [37]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [39]:
import numpy as np  #oin two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


<b>Joining Arrays Using Stack Functions</b>
- Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
- We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
- We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [40]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


<font size="6"> NumPy Splitting Array</font>

- Splitting is reverse operation of Joining.

- Joining merges multiple arrays into one and Splitting breaks one array into multiple.

- We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [41]:
import numpy as np    #Split the array in 3 parts:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [2]:
import numpy as np # Split the array in 4 parts:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


<b>Splitting 2-D Arrays</b>

In [5]:
import numpy as np  

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [6]:
import numpy as np  #Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


<b>Basic arithmetic operations</b>

In [7]:
# Consider 2 numpy arrays
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Y = np.array([[9, 1, 1],
              [3, 6, 9],
              [2, 6, 0]])

The constraints basic matrix algebra apply to numpy arrays as well. Some constraints are:
* Two matrices can be added or subtracted only if they have same shape.
* Two matrices can be multiplied if the last dimention of one matrix is same as the first dimention of other matrix i.e. the allowed shapes of matrices are $m \times k$ and $k \times n$. $m$ and $n$ can take different values.

In [8]:
# Addition
A = X + Y
B = X - Y
print('A : ')
print(A)
print('B : ')
print(B)

A : 
[[10  3  4]
 [ 7 11 15]
 [ 9 14  9]]
B : 
[[-8  1  2]
 [ 1 -1 -3]
 [ 5  2  9]]


In [9]:
# Multiplication

# 1st Implementation
C = A@B
print('C :')
print(C)

# 2nd Implementation
D = np.matmul(A, B)
print('D :')
print(D)

# 3rd Implementaiton
E = A.dot(B)
print('E :')
print(E)

C :
[[-57  15  47]
 [ 30  26 116]
 [-13  13  57]]
D :
[[-57  15  47]
 [ 30  26 116]
 [-13  13  57]]
E :
[[-57  15  47]
 [ 30  26 116]
 [-13  13  57]]


Taking the transpose of a matrix means swapping its two dimensions:  
the **rows become columns**, and the **columns become rows**.  
So, a matrix of shape `(m, n)` becomes `(n, m)` after transposing.  

This operation simply flips the matrix over its diagonal, turning each row into a column.  
For example, a 2×3 matrix becomes a 3×2 matrix after transpose.


In [10]:
# Transpose
M = np.array([[1, 2, 3],
              [4, 5, 6]])

# Method 1: Using .T
M_T = M.T
print('Method 1 :')
print(M_T)

# Method 2: Using np.transpose
M_T2 = np.transpose(M)
print('Method 2 :')
print(M_T2)

print(f'Shape of the output matrix : {M_T2.shape}')

Method 1 :
[[1 4]
 [2 5]
 [3 6]]
Method 2 :
[[1 4]
 [2 5]
 [3 6]]
Shape of the output matrix : (3, 2)


<b>Aggregations</B>

In [11]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Aggregation functions
print("Sum of all elements in A:", np.sum(A))
print("Mean of A:", np.mean(A))
print("Standard deviation of A:", np.std(A))
print("Minimum and Maximum of A:", np.min(A), np.max(A))
print("Index of maximum element in flattened A:", np.argmax(A))

Sum of all elements in A: 21
Mean of A: 3.5
Standard deviation of A: 1.707825127659933
Minimum and Maximum of A: 1 6
Index of maximum element in flattened A: 5


<b>Broadcasting in NumPy</B>

<b>Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes. It automatically expands smaller arrays to match the shape of larger ones without creating unnecessary copies.</b>

In [13]:
import numpy as np

# Scalar broadcasting
arr = np.array([1, 2, 3, 4])
result = arr + 10  # 10 is broadcast to [10, 10, 10, 10]
print(result)  # [11 12 13 14]

[11 12 13 14]


In [16]:
#Adding a Vector to a Matrix
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])  # shape (2, 3)
vector = np.array([10, 20, 30])   # shape (3,)

result = matrix + vector
print(result)

[[11 22 33]
 [14 25 36]]


In [17]:
arr1 = np.arange(5) 

In [18]:
print(arr1)

[0 1 2 3 4]


In [19]:
arr2 = np.arange(2, 7)  

In [20]:
print(arr2)

[2 3 4 5 6]


In [21]:
int_arr = np.array([1, 2, 3])
float_arr = int_arr.astype(float)

In [22]:
print(float_arr)

[1. 2. 3.]


In [23]:
float_arr = np.array([1.5, 2.7, 3.1])
int_arr = float_arr.astype(int) 

In [24]:
print(int_arr)

[1 2 3]


In [25]:
# Create template array
original = np.array([[1, 2, 3],
                      [4, 5, 6]])

In [26]:
# Create zeros with same shape
zeros = np.zeros_like(original)   
ones = np.ones_like(original)  

In [27]:
print(zeros)

[[0 0 0]
 [0 0 0]]


In [28]:
print(ones)

[[1 1 1]
 [1 1 1]]


In [29]:
r1 = np.random.random() 

In [30]:
print(r1)

0.14764179392140275


In [32]:
r2 = np.random.random(5)

In [33]:
print(r2)

[0.33551863 0.39196751 0.58887465 0.51439284 0.62046839]


In [34]:
r3 = np.random.random((3, 4))

In [35]:
print(r3)

[[0.31502537 0.97018846 0.59604443 0.25238266]
 [0.53700551 0.15985464 0.99366085 0.9768353 ]
 [0.491214   0.27147184 0.77888977 0.10689636]]


In [36]:
r4 = np.random.random((2, 3, 2))

In [37]:
print(r4)

[[[0.89278472 0.58959728]
  [0.29993661 0.99506236]
  [0.09508417 0.33945117]]

 [[0.20474115 0.59249933]
  [0.02653847 0.78648781]
  [0.71518284 0.5729605 ]]]


In [38]:
# Generate array of 5 integers
arr = np.random.randint(1, 101, 5)  # 5 numbers
print(arr)

[26 22 31 98 44]


<b>Statistical Operations in NumPy</b>

In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # 3.0


3.0


In [46]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [47]:
print(np.mean(matrix))

5.0


In [52]:
data = np.array([1, 2, 3, 100, 200,12])
print(np.median(data))

7.5


In [49]:
matrix = np.array([[1, 2, 10],
                   [4, 5, 20],
                   [7, 8, 30]])


In [50]:
print(np.median(matrix)) 

7.0


In [51]:
arr = np.array([[4, 2, 7],
                [1, 9, 3]])

In [53]:
print(np.min(arr)) 

1


In [54]:
print(np.max(arr))

9


In [55]:
arr = np.array([10, 20, 30, 40, 100])
data_range = np.ptp(arr)  # Peak-to-peak = max - min
print(data_range)

90
